config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :users
  resource :sessions, only: [:new, :create, :destroy]

  root :to => 'articles#home'
  get '/about' => 'articles#about_us'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :title, presence: true
  validates :picture, presence: true
  validates :content, presence: true

  def self.most_recent
    Article.all.sort_by{|article| article[:created_at]}.reverse.first(3)
  end

  def self.most_popular
    Article.all.sort_by{|article| article[:views]}.reverse.first(3)
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :authenticate_user, except: %i[home index show]

  def home
    @most_recent = Article.most_recent
    @most_popular = Article.most_popular
  end

  def index
    @articles = Article.all
  end

  def about_us
  end

  def show
    @article = Article.find_by(id: params[:id])
    @article.views += 1
    @article.save
  end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def create
    @category = Category.find_by(name: params[:article][:category])

    @article = Article.new(title: params[:article][:title], picture: params[:article][:picture], content: params[:article][:content], user_id: current_user.id, category: @category)


    if @article.save
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @article = Article.find_by(id: params[:id])
  end

  def update
    @article = Article.find_by(id: params[:id])
  end

  def destroy
    @article = Article.find_by(id: params[:id])
    @article.destroy
    redirect_to user_url(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(email: params[:user][:email], username: params[:user][:username], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    redirect_to user_url(@user)
  end

  def destroy
    @user = User.find_by(id: params[:id])
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/about_us.html.erb
<h2>About Us</h2>

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>

<div class="">
<%= f.label :title %>
<%= f.text_area :title %>
</div>

<div class="">
<%= f.label :picture %>
<%= f.text_area :picture %>
</div>

<div class="">
<%= f.label :content %>
<%= f.text_area :content %>
</div>

<div class="">
<%= f.label :category %>
<%= f.text_field :category %>
</div>

<div class="">
<%= f.submit %>
</div>

<% end %>

<ul>
<% @article.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>

app/views/articles/home.html.erb
<div class="most-popular-container">

<h1>Most Popular Articles</h1>
<% @most_popular.each do |article| %>
<div class="most-popular">
  <h3><%= article.title %></h3> <span>by: <%= link_to "#{article.user.username}", user_path(article.user)%></span>
  <br>
  <%= link_to article_path(article) do %>
  <%= image_tag article.picture, class: "article-image" %>
  <% end %>
</div>
<% end %>
</div>


<div class="most-recent-conainer">
<h1>Most Recent Articles</h1>
<% @most_recent.each do |article| %>
  <div class="most-recent">
  <h3><%= article.title %></h3> <span>by: <%= link_to "#{article.user.username}", user_path(article.user)%></span>
  <br>
  <%= link_to article_path(article) do %>
    <%= image_tag article.picture, class: "article-image" %>
  <% end %>
  </div>
<% end %>
</div>

app/views/articles/index.html.erb
<div class="most-recent-container">

<% @articles.each do |article| %>
<div class="most-recent">

<p> <%= article.category.name %> </p>
<h2> <%= article.title %> </h2>
<p>by: <%= article.user.username %> </p>

<p>
<%= link_to article_path(article) do %>
  <%= image_tag article.picture, class: "article-image" %>
<% end %>
</p>

<!-- <p> <%= article.content %> </p> -->

</div>

<% end %>


</div>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>

<div class="">
<%= f.label :title %>
<%= f.text_area :title %>
</div>

<div class="">
<%= f.label :picture %>
<%= f.text_area :picture %>
</div>

<div class="">
<%= f.label :content %>
<%= f.text_area :content %>
</div>

<div class="">
<%= f.label :category %>
<%= f.text_field :category %>
</div>

<div class="">
<%= f.submit %>
</div>

<% end %>

<ul>
<% @article.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>

app/views/articles/show.html.erb
<!-- <h1> <%= @article.category.name %> </h1> -->

<h2><%= @article.title %></h2>
<p>by: <%= link_to "#{@article.user.username}", user_path(@article.user)%></p>

<img src="<%= @article.picture %>" alt="<%= @article.title %>">
<br>
<button type="button" name="button">Like</button>
<br>
<p> <%= @article.content %> </p>

<% if current_user && current_user == @article.user %>
  <%= link_to 'Edit', edit_article_path %>
  <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure to delete this recipe?' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlmondSports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to root_path do %>
    <%= image_tag 'logofinal.png', id: "logo" %>
    <% end %>
    <nav class="navigation">

      <%= link_to 'Articles', articles_path %>
      <%= link_to 'About Us', about_path %>
      <% if !current_user %>
        <%= link_to 'Register', new_user_path %>
        <%= link_to 'Login', new_sessions_path %>
      <% else %>
        <%= link_to 'Logout', sessions_path, :method => :delete %>
        <%= link_to 'Profile', user_path(current_user) %>
      <% end %>
      <% if current_user && current_user.admin == true %>
        <%= link_to 'New Article', new_article_path %>
      <% end %>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
<div class="">
  Username: <%= user.username %><br>
  Email: <%= user.email %><br>
  Admin Status: <%= user.admin %>
</div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

<div class="">
<%= f.label :email %>
<%= f.text_field :email %>
</div>

<div class="">
<%= f.label :username %>
<%= f.text_field :username %>
</div>

<div class="">
<%= f.label :password %>
<%= f.password_field :password %>
</div>

<div class="">
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</div>

<div class="">
<%= f.submit 'Register' %>
</div>

<% end %>

<ul>
<% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>

app/views/users/show.html.erb
<% if current_user %>
<h1>Hello <%= @user.username %> ..</h1>
<% end %>

<% if current_user && current_user.admin == true %>
  <%= link_to 'All Users', users_path %>
<% end %>

<div class="most-recent-container">

<h2>Articles by <%= @user.username %></h2>
  <% @user.articles.each do |article| %>

    <div class="most-recent">
    <h3><%= article.title %></h3> <span>by: <%= link_to "#{article.user.username}", user_path(article.user)%></span>
    <br>
    <%= link_to article_path(article) do %>
      <%= image_tag article.picture, class: "article-image" %>
    <% end %>
    </div>
  <% end %>

</div>